repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.2
    hooks:
      - id: remove-print-statements
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/wemake-services/dotenv-linter
    rev: 0.2.0
    hooks:
      - id: dotenv-linter
